---
ansible_user: psight
ansible_python_interpreter: /usr/bin/python3
kubernetes_base_version: 1.29
kubernetes_kubeadm_version: "{{ kubernetes_base_version }}.1"
kubernetes_full_version: "{{ kubernetes_kubeadm_version }}-1.1"

# Uncomment the next two lines if you want touse Flannel instead of Calico (Calico is the default used b)
# You will want to use Flannel if you wish to use metallb later as calico is not compatible  work with metallb
#use_flannel: true
#pod_cidr: 10.244.0.0/16