---
- name: Master playbook for the course infrastructure
  import_playbook: playbooks/base.yml

- name: Kubectl autocompletion
  import_playbook: playbooks/cplane.yml

- name: Worker node configuration
  import_playbook: playbooks/workers.yml
