- name: install libguestfs tools
  apt:
    name: 
    - libguestfs-tools
    state: present
    update_cache: yes
    cache_valid_time: 3600
  
- name: add install agent
  ansible.builtin.shell: |
    virt-customize -a {{ isopath }}/{{ item.templateName }}.qcow2 --install qemu-guest-agent
  loop: "{{ cloudimgs }}"

- name: add ansible
  ansible.builtin.shell: |
    virt-customize -a {{ isopath }}/{{ item.templateName }}.qcow2 --install ansible
  loop: "{{ cloudimgs }}"  
  
- name: fix machine id
  ansible.builtin.shell: |
    virt-customize -a {{ isopath }}/{{ item.templateName }}.qcow2 --run {{ isopath }}/clear-machine-id.sh
  loop: "{{ cloudimgs }}"

- name: resize cloud-init images
  ansible.builtin.command: "qemu-img resize {{ isopath }}/{{ item.templateName }}.qcow2 {{ templateDiskSize }}"
  loop: "{{ cloudimgs }}"