---
- name: Install libguestfs tools
  ansible.builtin.apt:
    name:
      - libguestfs-tools
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add install agent
  ansible.builtin.command: |
    virt-customize -a {{ isopath }}/{{ cloudimg.template_name }}.qcow2 --install qemu-guest-agent
  changed_when: true

- name: Add ansible
  ansible.builtin.command: |
    virt-customize -a {{ isopath }}/{{ cloudimg.template_name }}.qcow2 --install ansible
  changed_when: true

- name: Fix machine id
  ansible.builtin.command: |
    virt-customize -a {{ isopath }}/{{ cloudimg.template_name }}.qcow2 --run {{ isopath }}/clear-machine-id.sh
  changed_when: true

- name: Resize cloud-init images
  ansible.builtin.command: "qemu-img resize {{ isopath }}/{{ cloudimg.template_name }}.qcow2 {{ template_disk_size }}"
  changed_when: true
