---
- name: Import kubeadm tasks
  ansible.builtin.import_tasks: kubeadm.yml

- name: Include Calico CNI tasks
  ansible.builtin.include_tasks: calico.yml
  when: not use_flannel

- name: Include Flannel CNI tasks
  ansible.builtin.include_tasks: flannel.yml
  when: use_flannel

- name: Import kubectl completion tasks
  ansible.builtin.import_tasks: kubectl.yml
