---
# vars file
isopath: /var/isos
templateMemory: 2048
templateCores: 2
templateDiskSize: 32G
templateStartingID: 8000
importStorage: local-lvm #iscsi-lvm
cloudimgs:
  - url: https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img
    templateName: ubuntu-24.04-server
ciuser: psight # cloud-init user
# if you choose to use ip=dhcp you will probably need to configure a fixed ip in the dhcp settings of your router
#ipconfig0: ip=dhcp # ip6=auto,ip=dhcp
ipconfig0: "ip=192.168.50.0/24,gw=192.168.50.0" # ip6=auto,ip=dhcp
sshkey: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
