---
ansible_user: psight
ansible_python_interpreter: /usr/bin/python3
kubernetes_base_version: 1.29
kubernetes_kubeadm_version: "{{ kubernetes_base_version }}.1"
kubernetes_full_version: "{{ kubernetes_kubeadm_version }}-1.1"
