---
- name: Copy modprobe k8s.conf to /etc/modules-load.d
  ansible.builtin.copy:
    src: modprobe.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: "0644"

- name: Run modprobe overlay
  ansible.builtin.command:
    cmd: modprobe --first-time overlay
  register: modprobe_overlay
  changed_when: modprobe_overlay.stderr.find('already in kernel') == -1
  failed_when: false

- name: Run modprobe br_netfilter
  ansible.builtin.command:
    cmd: modprobe --first-time br_netfilter
  register: modprobe_br_netfilter
  changed_when: modprobe_br_netfilter.stderr.find('already in kernel') == -1
  failed_when: false

- name: Copy sysctl k8s.conf to /etc/sysctl.d/k8s.conf
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: "0644"

- name: Apply sysctl settings
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: false
