---
- name: Set machine property options fact
  ansible.builtin.set_fact:
    machine_options: "--memory {{ template_memory }} --core {{ template_cores }} --name {{ cloudimg.template_name }} --net0 virtio,bridge=vmbr0"

- name: Set machine name options fact
  ansible.builtin.set_fact:
    machine_name_options: "--name {{ cloudimg.template_name }} --description '{{ template_note }}'"

- name: Create VMs
  ansible.builtin.command:
    cmd: "qm create {{ next_vm_id }} {{ machine_options }} {{ machine_name_options }}"
  register: command_result
  failed_when:
    - '"already exists" not in command_result.stderr'
    - command_result.rc != 0
  changed_when: true

- name: Copy ssh key to proxmox
  ansible.builtin.copy:
    content: "{{ sshkey }}"
    dest: "{{ isopath }}/id_rsa.pub"
    owner: root
    group: root
    mode: "0644"

- name: Debug - show nameserver
  ansible.builtin.debug:
    msg: "Nameserver is {{ nameserver }}"    

- name: Set cloud init settings
  ansible.builtin.script: "config.sh {{ next_vm_id }} {{ ipconfig0 }} {{nameserver}} {{ isopath }}/id_rsa.pub {{ ciuser }} {{ import_storage }} {{ isopath }}/{{ cloudimg.template_name }}.qcow2"  # noqa: yaml[line-length]
  register: config
  changed_when: "'Skipping' not in config.stdout"

- name: Convert to template
  when: true
  ansible.builtin.command:
    cmd: qm template {{ next_vm_id }}
  changed_when: true
